### ISSUE TITLE
Retrieve all the files by accession and file type

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pridepy#1]
Retrieve all the files

**Filter by:**

- Accession

- File Type(RESULT/PEAK/SEARCH/OTHER)

**Returns:**

- List of file names

**Comment by ypriverol** [comment]
Do we want to provide also a command line tool that enable to bulk the information into files: 

- [ ] Print the output of an option in the SdT 
- [ ] Output the results of a query into a file.
