### ISSUE TITLE
Installation via pip

### ISSUE THREAD

**Issue by gessulat** [PRIDE-Archive/pridepy#4]
I noticed that the command given in the README 'pip install --upgrade pride-py' does not work for me, because pip cannot find a repository 'pride-py'. Using 'pip install --upgrade .' in the repository instead works as it picks up the information from the setup.py. 

Not sure if there is something wrong on my end, or if you would like to change the README. 

Thanks for your work!

**Comment by ypriverol** [comment]
@gessulat We have spend some time in the package https://pypi.org/project/pridepy/ adding new features etc. Can you try it and let us know if it works well for you.

**Comment by qiz218591** [comment]
The codes, you provided are not working. When i specify my path to download all raw files then it usually giving me "extra path" added like this. Which is seriously I didnt undertsand, why this is giving me. Can you please solve this issues?
I am able to do pip install pridepy as well as upgraded it. But coudnt able to download the raw files from the codes which you guys specified. Would highly appreciate your help as well as feedbacks in this regards. Meanwhile, as a note, I would like to say that I am trying to use R but it is a lot of time to download the files also when i have tried to see the file folder then it was empty, I dont know why ?? Any suggestions in this regards? I can forward the R code. If there is any requirements to solve this issue. (For knowledge- i used rpx package)

**Comment by selvaebi** [comment]
@qiz218591 May i know what command are you using. Thanks.

**Comment by selvaebi** [comment]
hi i tried your command
 ```C02ZG0U2L414:prideftp selva$ pridepy download-all-raw-files -a PXD041748 -o /Users/Divya Agrawal/Downloads/pride/
Usage: pridepy download-all-raw-files [OPTIONS]
Try 'pridepy download-all-raw-files --help' for help.

Error: Got unexpected extra argument (Agrawal/Downloads/pride/)

Please dont use space in output path
```


I tried in my local for my 
pridepy download-all-raw-files -a PXD041748 -o /Users/selva/prideftp/ it is working. 
The files are large so its taking time to download. But its working for me

**Comment by qiz218591** [comment]
Thanks, I tried to, it worked
